name: ties20
channels:
  - conda-forge
  - adw62
dependencies:
  - ambertools>=20.0, <22.0
  - libgfortran
  - ties_md
  - numpy
  - cython
  - setuptools
  - matplotlib
  - networkx
  - dwave_networkx
  - dimod
  - tabulate
  - pip:
      - . # ties installation
