name: ties
channels:
  - conda-forge
  - defaults

dependencies:
  - conda-forge::ambertools >=20.0
  - ties_md
  - numpy <=1.23.5
  - cython
  - setuptools
  - matplotlib
  - networkx
  - dimod
  - tabulate
  - dwave-networkx
