name: test
channels:
  - conda-forge
dependencies:
  - pip
  - ambertools>=20.0, <22.0
  - libgfortran
  - ties_md
  - numpy
  - cython
  - setuptools
  - matplotlib
  - networkx
  - dimod
  - tabulate
  - pip:
      - dwave_networkx
      #- . # ties installation
