name: ties
channels:
  - conda-forge
  - defaults

dependencies:
  - conda-forge::ambertools >=21.0
  - ties_md
  - numpy==1.23.5 # fixme? 
  - cython
  - setuptools
  - matplotlib
  - networkx
  - tabulate
  - MDAnalysis
