name: ties
channels:
  - conda-forge
  - defaults

dependencies:
  - conda-forge::ambertools >=21.0
  - setuptools
  - matplotlib
  - networkx
  - tabulate
  - MDAnalysis
  - dimod
  - numpy < 2.3 # temporary fix until Parmed moves away from the removed numpy.compat
