name: ties
channels:
  - conda-forge
  - defaults
  -
dependencies:
  - ambertools>=20.0, <22.0
  - libgfortran
  - ties_md
  - numpy
  - cython
  - setuptools
  - matplotlib
  - networkx
  - dimod
  - tabulate
  - dwave-networkx
