site_name: "TIES"
site_description: "Software for Relative Binding Free Energy calculations"
site_url: "https://github.com/UCL-CCS/TIES"
repo_url: "https://github.com/UCL-CCS/TIES"
repo_name: "UCL-CCS/TIES"
site_dir: "site"
watch: [mkdocs.yml, README.md, ties/, docs]
copyright: Copyright &copy; 2025 Mateusz Bieniek
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

extra:
  version:
    provider: mike

nav:
- Home:
  - Overview: index.md
  - Publications: publications.md
  - WebTIES: webties.md
- Usage: usage.md
- API reference: reference/
- Theory:
  - Theory: theory.md
  - Superimposition: superimposition.md

#theme:
#  name: material
##  - toc.follow
#  palette:
#    primary: light blue

theme:
  name: material
  features:
  - announce.dismiss
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
#    scheme: default
    primary: light blue
  favicon: docs/images/favicon.png


#markdown_extensions:
#- attr_list
#- md_in_html
#- def_list
#- admonition
#- footnotes
#- pymdownx.highlight:
#    anchor_linenums: true
#    line_spans: __span
#    pygments_lang_class: true
#- pymdownx.inlinehilite
#- pymdownx.superfences
#- pymdownx.magiclink
#- pymdownx.snippets:
#    check_paths: true
#- pymdownx.details
#- pymdownx.arithmatex:
#    generic: true
#- pymdownx.tabbed:
#    alternate_style: true
#- toc:
#    permalink: "#"

plugins:
- autorefs
- search
- bibtex:
    bib_file: "docs/references.bib"
#- mkdocstrings:
#    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
#    default_handler: python
#    handlers:
#      python:
#        paths: [ties/]
#        options:
#          show_source: false
#          show_submodules: true
#          show_labels: true
- gen-files:
    scripts:
    - docs/scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    handlers:
      python:
        paths: [ties/]
        import:
          - https://parmed.github.io/ParmEd/html/objects.inv
          - http://docs.openmm.org/latest/api-python/objects.inv
          - https://www.mdtraj.org/1.9.6/objects.inv
        options:
          extensions: [ griffe_pydantic ]
          docstring_options:
            ignore_init_summary: true
            returns_multiple_items: false
            returns_named_value: false
          docstring_section_style: list
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          summary: true
          members_order: source

#extra_javascript:
#  - javascripts/mathjax.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js